import React from 'react';
import { PredictionResponse, FinancialProfile } from '../types';
import { Sparkles, TrendingUp, Shield, Clock, Wallet, DollarSign, RotateCcw, AlertTriangle } from 'lucide-react';

interface PredictionResultsProps {
  result: PredictionResponse;
  submittedProfile: FinancialProfile;
  onReset: () => void;
}

export const PredictionResults: React.FC<PredictionResultsProps> = ({ result, submittedProfile, onReset }) => {
  // Use predicted_corpus from API response
  const predictedCorpus = result.predicted_corpus || result.Future_Corpus || result.required_corpus || 0;
  const metrics = result.metrics;

  const formatCurrency = (amount: number) => {
    if (amount >= 10000000) {
      return `₹ ${(amount / 10000000).toFixed(2)} Crores`;
    } else if (amount >= 100000) {
      return `₹ ${(amount / 100000).toFixed(2)} Lakhs`;
    }
    return `₹ ${amount.toLocaleString('en-IN')}`;
  };

  const yearsRemaining = submittedProfile.retirement_age - submittedProfile.age;
  const currentTotalCorpus = submittedProfile.current_savings + submittedProfile.existing_investments;
  const monthlySurplus = Math.max(0, submittedProfile.monthly_income - submittedProfile.monthly_expenses);

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Top Banner Card */}
      <div className="glass-card p-8 rounded-3xl relative overflow-hidden border border-indigo-500/30">
        <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-600/10 blur-[100px] rounded-full pointer-events-none" />

        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 relative z-10">
          <div>
            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-indigo-950/80 border border-indigo-800/80 text-indigo-300 text-xs font-semibold mb-3">
              <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
              <span>ML Model Prediction Complete</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-white">Your AI Retirement Projection</h2>
            <p className="text-xs sm:text-sm text-slate-400 mt-1">
              Estimated target corpus generated by our trained Gradient Boosting Regressor model
            </p>
          </div>

          <button
            onClick={onReset}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-900 border border-slate-700 text-slate-200 text-xs font-semibold hover:bg-slate-800 transition-colors"
          >
            <RotateCcw className="h-3.5 w-3.5" />
            <span>Edit Financial Inputs</span>
          </button>
        </div>

        {/* Large Corpus Value Display */}
        <div className="mt-8 p-6 rounded-2xl bg-gradient-to-r from-indigo-950/80 via-slate-900/90 to-slate-950/80 border border-indigo-500/30">
          <p className="text-xs uppercase tracking-wider font-semibold text-indigo-300 mb-2">
            Predicted Future Retirement Corpus
          </p>
          <div className="text-4xl sm:text-5xl lg:text-6xl font-black text-white tracking-tight gradient-text">
            {formatCurrency(predictedCorpus)}
          </div>
          <p className="text-xs text-slate-400 mt-2">
            Exact Raw Value: ₹ {predictedCorpus.toLocaleString('en-IN', { maximumFractionDigits: 2 })}
          </p>
        </div>
      </div>

      {/* Grid of Key Metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Metric 1: Risk Profile */}
        <div className="glass-card p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-400">
              <Shield className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-slate-400">ML Risk Profile</span>
          </div>
          <p className="text-2xl font-bold text-white capitalize">{result.risk_profile || submittedProfile.risk_tolerance}</p>
          <p className="text-[11px] text-slate-400 mt-1">Derived by Logistic Classifier</p>
        </div>

        {/* Metric 2: Current Total Corpus */}
        <div className="glass-card p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <Wallet className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-slate-400">Current Total Wealth</span>
          </div>
          <p className="text-xl font-bold text-white">{formatCurrency(currentTotalCorpus)}</p>
          <p className="text-[11px] text-slate-400 mt-1">Savings + Investments</p>
        </div>

        {/* Metric 3: Monthly Surplus */}
        <div className="glass-card p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400">
              <DollarSign className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-slate-400">Monthly Surplus</span>
          </div>
          <p className="text-xl font-bold text-white">₹ {monthlySurplus.toLocaleString('en-IN')}</p>
          <p className="text-[11px] text-slate-400 mt-1">Income - Expenses</p>
        </div>

        {/* Metric 4: Years Remaining */}
        <div className="glass-card p-6 rounded-2xl">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-lg bg-amber-500/10 border border-amber-500/20 text-amber-400">
              <Clock className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-slate-400">Investment Horizon</span>
          </div>
          <p className="text-2xl font-bold text-white">{yearsRemaining} Years</p>
          <p className="text-[11px] text-slate-400 mt-1">Retire at age {submittedProfile.retirement_age}</p>
        </div>

      </div>

      {/* Analytical Breakdown Metrics (If present in API metrics response) */}
      {metrics && (
        <div className="glass-card p-6 rounded-2xl space-y-6">
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-indigo-400" />
            <span>Retirement Goal Analysis & Coverage</span>
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <p className="text-xs text-slate-400 mb-1">Projected Wealth Accumulation</p>
              <p className="text-lg font-bold text-emerald-400">{formatCurrency(metrics.projected_corpus)}</p>
            </div>

            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <p className="text-xs text-slate-400 mb-1">Funding Shortfall Gap</p>
              <p className="text-lg font-bold text-rose-400">{formatCurrency(metrics.funding_gap)}</p>
            </div>

            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <p className="text-xs text-slate-400 mb-1">Retirement Readiness Index</p>
              <p className="text-lg font-bold text-indigo-400">{metrics.readiness_score} / 100</p>
            </div>
          </div>
        </div>
      )}

      {/* Submitted Financial Summary Table */}
      <div className="glass-card p-6 rounded-2xl">
        <h3 className="text-base font-bold text-white mb-4">Submitted Financial Profile Parameters</h3>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
          <div>
            <span className="text-slate-400">Current Age:</span>
            <p className="font-semibold text-white">{submittedProfile.age} yrs</p>
          </div>
          <div>
            <span className="text-slate-400">Retirement Age:</span>
            <p className="font-semibold text-white">{submittedProfile.retirement_age} yrs</p>
          </div>
          <div>
            <span className="text-slate-400">Monthly Income:</span>
            <p className="font-semibold text-white">₹ {submittedProfile.monthly_income.toLocaleString('en-IN')}</p>
          </div>
          <div>
            <span className="text-slate-400">Monthly Expenses:</span>
            <p className="font-semibold text-white">₹ {submittedProfile.monthly_expenses.toLocaleString('en-IN')}</p>
          </div>
          <div>
            <span className="text-slate-400">Liquid Savings:</span>
            <p className="font-semibold text-white">₹ {submittedProfile.current_savings.toLocaleString('en-IN')}</p>
          </div>
          <div>
            <span className="text-slate-400">Existing Investments:</span>
            <p className="font-semibold text-white">₹ {submittedProfile.existing_investments.toLocaleString('en-IN')}</p>
          </div>
          <div>
            <span className="text-slate-400">Inflation Assumption:</span>
            <p className="font-semibold text-white">{(submittedProfile.expected_inflation_rate * 100).toFixed(1)}%</p>
          </div>
          <div>
            <span className="text-slate-400">Expected Annual ROI:</span>
            <p className="font-semibold text-white">{(submittedProfile.expected_roi * 100).toFixed(1)}%</p>
          </div>
        </div>
      </div>
    </div>
  );
};
